import {PolySceneWithNodeMap_scene_01} from '../autogenerated/PolySceneWithNodeMap';

export class LightsController {
	constructor(private scene: PolySceneWithNodeMap_scene_01) {}
	init() {
		this._setupSpotlightShadow();
	}
	private _setupSpotlightShadow() {
		const node = this.scene.node('/spotLight1');
		const param = node.p.shadowUpdateOnNextRender;
		param.set(1);
		setTimeout(() => {
			param.set(0);
		}, 1000);
	}
}
