import {PolySceneWithNodeMap_scene_01} from '../autogenerated/PolySceneWithNodeMap';
import {ControlsToggler} from './controlsToggler';
import {LightsController} from './lights';
import {PlaylistController} from './playlist';

let sceneReady: boolean = false;

const playlistController = new PlaylistController();

export function setup() {
	playlistController.setupSoundNoticeEvents();
	document.addEventListener('POLYSceneReady', (event) => {
		sceneReady = true;
		const scene: PolySceneWithNodeMap_scene_01 = (event as any).detail.scene;
		const lightsController = new LightsController(scene);

		lightsController.init();
		playlistController.setScene(scene);
		playlistController.onSceneReadyAndUserActionPerformed();

		new ControlsToggler();
	});
}
